#!/usr/bin/env node

/**
 * Setup Environment Script
 *
 * Runs `supabase status` to extract local development keys
 * and writes them to .env.local
 *
 * Usage: node scripts/setup_env.cjs
 */

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const ENV_FILE = path.join(__dirname, '..', '.env.local');
const ENV_EXAMPLE = path.join(__dirname, '..', '.env.example');

function log(message) {
  console.log(`[setup_env] ${message}`);
}

function error(message) {
  console.error(`[setup_env] ERROR: ${message}`);
}

function getSupabaseStatus() {
  log('Running supabase status...');

  try {
    const output = execSync('supabase status', {
      encoding: 'utf-8',
      stdio: ['pipe', 'pipe', 'pipe'],
    });
    return output;
  } catch (err) {
    if (err.stderr && err.stderr.includes('not running')) {
      error('Supabase is not running. Start it with: supabase start');
      process.exit(1);
    }
    if (err.message.includes('command not found') || err.message.includes('ENOENT')) {
      error('Supabase CLI not found. Install it from: https://supabase.com/docs/guides/cli');
      process.exit(1);
    }
    // Some versions output to stderr even on success
    if (err.stdout) {
      return err.stdout;
    }
    throw err;
  }
}

function parseSupabaseStatus(output) {
  const values = {};

  // Parse API URL
  const apiUrlMatch = output.match(/API URL:\s*(http[^\s]+)/);
  if (apiUrlMatch) {
    values.NEXT_PUBLIC_SUPABASE_URL = apiUrlMatch[1];
  }

  // Parse anon key (new CLI uses "Publishable key", old CLI used "anon key")
  const anonKeyMatch = output.match(/(?:anon key|Publishable key):\s*([^\s]+)/i);
  if (anonKeyMatch) {
    values.NEXT_PUBLIC_SUPABASE_ANON_KEY = anonKeyMatch[1];
  }

  // Parse service_role key (new CLI uses "Secret key", old CLI used "service_role key")
  const serviceRoleMatch = output.match(/(?:service_role key|Secret key):\s*([^\s]+)/i);
  if (serviceRoleMatch) {
    values.SUPABASE_SERVICE_ROLE_KEY = serviceRoleMatch[1];
  }

  // Parse Studio URL (optional, for reference)
  const studioUrlMatch = output.match(/Studio URL:\s*(http[^\s]+)/);
  if (studioUrlMatch) {
    values._STUDIO_URL = studioUrlMatch[1];
  }

  return values;
}

function readExistingEnv() {
  if (fs.existsSync(ENV_FILE)) {
    log('Reading existing .env.local...');
    const content = fs.readFileSync(ENV_FILE, 'utf-8');
    const env = {};

    content.split('\n').forEach(line => {
      // Skip comments and empty lines
      if (line.startsWith('#') || !line.trim()) {
        return;
      }

      const match = line.match(/^([^=]+)=(.*)$/);
      if (match) {
        env[match[1].trim()] = match[2].trim();
      }
    });

    return env;
  }

  // If no .env.local exists, try to read from .env.example
  if (fs.existsSync(ENV_EXAMPLE)) {
    log('No .env.local found, using .env.example as template...');
    const content = fs.readFileSync(ENV_EXAMPLE, 'utf-8');
    const env = {};

    content.split('\n').forEach(line => {
      if (line.startsWith('#') || !line.trim()) {
        return;
      }

      const match = line.match(/^([^=]+)=(.*)$/);
      if (match) {
        // Only keep the key, we'll replace the value
        env[match[1].trim()] = match[2].trim();
      }
    });

    return env;
  }

  return {};
}

function writeEnvFile(env) {
  const lines = [
    '# Supabase Configuration',
    '# Generated by scripts/setup_env.cjs',
    `# Last updated: ${new Date().toISOString()}`,
    '',
    '# Supabase Local Development',
    `NEXT_PUBLIC_SUPABASE_URL=${env.NEXT_PUBLIC_SUPABASE_URL || ''}`,
    `NEXT_PUBLIC_SUPABASE_ANON_KEY=${env.NEXT_PUBLIC_SUPABASE_ANON_KEY || ''}`,
    '',
    '# Server-side only (do not expose to client)',
    `SUPABASE_SERVICE_ROLE_KEY=${env.SUPABASE_SERVICE_ROLE_KEY || ''}`,
    '',
    '# App Configuration',
    `NEXT_PUBLIC_APP_URL=${env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000'}`,
    '',
  ];

  // Add any additional custom variables that might exist
  const standardKeys = [
    'NEXT_PUBLIC_SUPABASE_URL',
    'NEXT_PUBLIC_SUPABASE_ANON_KEY',
    'SUPABASE_SERVICE_ROLE_KEY',
    'NEXT_PUBLIC_APP_URL',
    '_STUDIO_URL',
  ];

  const customVars = Object.entries(env).filter(
    ([key]) => !standardKeys.includes(key)
  );

  if (customVars.length > 0) {
    lines.push('# Custom Variables');
    customVars.forEach(([key, value]) => {
      lines.push(`${key}=${value}`);
    });
    lines.push('');
  }

  fs.writeFileSync(ENV_FILE, lines.join('\n'));
  log(`Written to ${ENV_FILE}`);
}

function main() {
  console.log('');
  console.log('========================================');
  console.log('  Froggie Frame - Environment Setup');
  console.log('========================================');
  console.log('');

  // Get supabase status
  const status = getSupabaseStatus();

  // Parse the output
  const supabaseValues = parseSupabaseStatus(status);

  if (!supabaseValues.NEXT_PUBLIC_SUPABASE_URL) {
    error('Could not parse API URL from supabase status');
    console.log('\nRaw output:');
    console.log(status);
    process.exit(1);
  }

  if (!supabaseValues.NEXT_PUBLIC_SUPABASE_ANON_KEY) {
    error('Could not parse anon key from supabase status');
    process.exit(1);
  }

  if (!supabaseValues.SUPABASE_SERVICE_ROLE_KEY) {
    error('Could not parse service_role key from supabase status');
    process.exit(1);
  }

  // Read existing env file
  const existingEnv = readExistingEnv();

  // Merge values (supabase values override existing)
  const mergedEnv = {
    ...existingEnv,
    NEXT_PUBLIC_SUPABASE_URL: supabaseValues.NEXT_PUBLIC_SUPABASE_URL,
    NEXT_PUBLIC_SUPABASE_ANON_KEY: supabaseValues.NEXT_PUBLIC_SUPABASE_ANON_KEY,
    SUPABASE_SERVICE_ROLE_KEY: supabaseValues.SUPABASE_SERVICE_ROLE_KEY,
  };

  // Write the env file
  writeEnvFile(mergedEnv);

  // Print summary
  console.log('');
  console.log('Environment configured successfully!');
  console.log('');
  console.log('Supabase Local URLs:');
  console.log(`  API URL:    ${supabaseValues.NEXT_PUBLIC_SUPABASE_URL}`);
  if (supabaseValues._STUDIO_URL) {
    console.log(`  Studio:     ${supabaseValues._STUDIO_URL}`);
  }
  console.log('');
  console.log('Next steps:');
  console.log('  1. Run the database migrations in Supabase Studio');
  console.log('  2. Start the dev server: npm run dev');
  console.log('');
}

// Run the script
main();
